fantasy_adj = ['Ancient',
               'Bat-infested',
               'Cavernous',
               'Chilly',
               'Clammy',
               'Cold',
               'Cramped',
               'Creaking',
               'Creepy',
               'Cursed',
               'Damp',
               'Dank',
               'Dark',
               'Decayed',
               'Dim',
               'Dingy',
               'Dismal',
               'Disorienting',
               'Disturbing',
               'Drafty',
               'Dripping',
               'Dusty',
               'Earthen',
               'Eerie',
               'Evil',
               'Flooded',
               'Formerly Resplendent',
               'Gargoyle-studded',
               'Gloomy',
               'Glowing',
               'Haunted',
               'Hidden',
               'Hideous',
               'Icy',
               'Illusory',
               'Inexplicable',
               'Malevolent',
               'Moldering',
               'Moldy',
               'Murky',
               'Musty',
               'Mysterious',
               'Odiferous',
               'Ominous',
               'Oppressive',
               'Polluted',
               'Roach-infested',
               'Ruined',
               'Rustling',
               'Scorched',
               'Silent',
               'Sinister',
               'Slimy',
               'Snake-infested',
               'Spectral',
               'Spooky',
               'Squalid',
               'Stained',
               'Stone',
               'Strangely Warm',
               'Uncanny',
               'Unsettling',
               'Vaulted']

fantasy_rooms = ['Armory',
                 'Bakehouse',
                 'Ballroom',
                 'Barracks',
                 'Basement',
                 'Bedroom',
                 'Brewery',
                 'Bunker',
                 'Buttery',
                 'Canal',
                 'Cave',
                 'Cavern',
                 'Cell',
                 'Cellar',
                 'Chamber',
                 'Chapel',
                 'Closet',
                 'Conservatory',
                 'Crawlspace',
                 'Crypt',
                 'Dining Room',
                 'Dressing Room',
                 'Dungeon',
                 'Egg Interior',
                 'Fighting Ring',
                 'Gallery',
                 'Garderobe',
                 'Gatehouse',
                 'Great Hall',
                 'Hall',
                 'Hall of Mirrors',
                 'Kitchen',
                 'Larder',
                 'Laundry',
                 'Library',
                 'Nursery',
                 'Office',
                 'Oubliette',
                 'Pantry',
                 'Parlor',
                 'Passageway',
                 'Pit',
                 'Priest Hole',
                 'Rib Cage',
                 'Sanctum',
                 'Scriptorium',
                 'Scullery',
                 'Secret Passage',
                 'Smithy',
                 'Stairwell',
                 'Stillroom',
                 'Study',
                 'Theater',
                 'Washroom',
                 'Wine Cellar',
                 'Workshop']
