scifi_adj = [
    'Shiny',
    'Chrome',
    'Rancid',
    'Smelly',
    'Bright', 
    'Dim',
    'Humming',
    'Neglected',
    'Hot',
    'Cold',
    'Alchemical',
    'Derelict',
    'Reinforced',
    'Radioactive',
    'Irradiated',
    'Slime Covered',
    'Alien',
    'Torched',
    'Bio',
    'Clean',
    'Dirty',
    'Turbo',
    'Frozen',
    'Exotic',
    'Holo',
    'Hydroponic',
    'Lush',
    'Complicated',
    'Blindingly Lit',
    'Graffitied',
    'Trashed',
    'Burgled',
    'Vandalized',
    'Toxic',
    'Infested',
    'Medical',
    'Bionic',
    'Xeno',
    'Resonating',
]

scifi_nouns = [
    'Airlock',
    'Galley',
    'Mess Hall',
    'Barracks',
    'Hallway',
    'Reactor',
    'Lab',
    'Laboratory',
    'Exam Room',
    'Operating Room',
    'Kitchen',
    'Supply Room',
    'Supply Closet',
    'Class Room',
    'Training Room',
    'Gym',
    'Armory',
    'Refinery',
    'Dish Pit',
    'Clean Room',
    'Pantry',
    'Cargo Bay',
    'Cockpit',
    'Bridge',
    'Engine Room',
    'Nursery',
    'Hatchery',
    'Garage',
    'Hanger',
    'Corridor',
    'Bedroom',
    'Brig',
    'Torture Chamber',
    'Generator',
    'Cryo Chamber',
    'Data Bank',
    'Server Room',
    'Crawl Space',
    'Life Support Chamber',
    'Office',
    'Security Station',
    'Bathroom',
    'Service Tunnel',
    'Map Room',
    'Habitat',
]
