import random

fantasy_adj = ['Ancient',
               'Bat-infested',
               'Cavernous',
               'Chilly',
               'Clammy',
               'Cold',
               'Cramped',
               'Creaking',
               'Creepy',
               'Cursed',
               'Damp',
               'Dank',
               'Dark',
               'Decayed',
               'Dim',
               'Dingy',
               'Dismal',
               'Disorienting',
               'Disturbing',
               'Drafty',
               'Dripping',
               'Dusty',
               'Earthen',
               'Eerie',
               'Evil',
               'Flooded',
               'Formerly Resplendent',
               'Gargoyle-studded',
               'Gloomy',
               'Glowing',
               'Haunted',
               'Hidden',
               'Hideous',
               'Icy',
               'Illusory',
               'Inexplicable',
               'Malevolent',
               'Moldering',
               'Moldy',
               'Murky',
               'Musty',
               'Mysterious',
               'Odiferous',
               'Ominous',
               'Oppressive',
               'Polluted',
               'Roach-infested',
               'Ruined',
               'Rustling',
               'Scorched',
               'Silent',
               'Sinister',
               'Slimy',
               'Snake-infested',
               'Spectral',
               'Spooky',
               'Squalid',
               'Stained',
               'Stone',
               'Strangely Warm',
               'Uncanny',
               'Unsettling',
               'Vaulted']

fantasy_rooms = ['Armory',
                 'Bakehouse',
                 'Ballroom',
                 'Barracks',
                 'Basement',
                 'Bedroom',
                 'Brewery',
                 'Bunker',
                 'Buttery',
                 'Canal',
                 'Cave',
                 'Cavern',
                 'Cell',
                 'Cellar',
                 'Chamber',
                 'Chapel',
                 'Closet',
                 'Conservatory',
                 'Crawlspace',
                 'Crypt',
                 'Dining Room',
                 'Dressing Room',
                 'Dungeon',
                 'Egg Interior',
                 'Fighting Ring',
                 'Gallery',
                 'Garderobe',
                 'Gatehouse',
                 'Great Hall',
                 'Hall',
                 'Hall of Mirrors',
                 'Kitchen',
                 'Larder',
                 'Laundry',
                 'Library',
                 'Nursery',
                 'Office',
                 'Oubliette',
                 'Pantry',
                 'Parlor',
                 'Passageway',
                 'Pit',
                 'Priest Hole',
                 'Rib Cage',
                 'Sanctum',
                 'Scriptorium',
                 'Scullery',
                 'Secret Passage',
                 'Smithy',
                 'Stairwell',
                 'Stillroom',
                 'Study',
                 'Theater',
                 'Washroom',
                 'Wine Cellar',
                 'Workshop']

scifi_adj = [
    'Shiny',
    'Chrome',
    'Rancid',
    'Smelly',
    'Bright', 
    'Dim',
    'Humming',
    'Neglected',
    'Hot',
    'Cold',
    'Alchemical',
    'Derelict',
    'Reinforced',
    'Radioactive',
    'Irradiated',
    'Slime Covered',
    'Alien',
    'Torched',
    'Bio',
    'Clean',
    'Dirty',
    'Turbo',
    'Frozen',
    'Exotic',
    'Holo',
    'Hydroponic',
    'Lush',
    'Complicated',
    'Blindingly Lit',
    'Graffitied',
    'Trashed',
    'Burgled',
    'Vandalized',
    'Toxic',
    'Infested',
    'Medical',
    'Bionic',
    'Xeno',
    'Resonating',
]

scifi_rooms = [
    'Airlock',
    'Galley',
    'Mess Hall',
    'Barracks',
    'Hallway',
    'Reactor',
    'Lab',
    'Laboratory',
    'Exam Room',
    'Operating Room',
    'Kitchen',
    'Supply Room',
    'Supply Closet',
    'Class Room',
    'Training Room',
    'Gym',
    'Armory',
    'Refinery',
    'Dish Pit',
    'Clean Room',
    'Pantry',
    'Cargo Bay',
    'Cockpit',
    'Bridge',
    'Engine Room',
    'Nursery',
    'Hatchery',
    'Garage',
    'Hanger',
    'Corridor',
    'Bedroom',
    'Brig',
    'Torture Chamber',
    'Generator',
    'Cryo Chamber',
    'Data Bank',
    'Server Room',
    'Crawl Space',
    'Life Support Chamber',
    'Office',
    'Security Station',
    'Bathroom',
    'Service Tunnel',
    'Map Room',
    'Habitat',
]

def makename(genre='fantasy'):
    if genre == 'fantasy':
        return f'{random.choice(fantasy_adj)} {random.choice(fantasy_rooms)}'
    if genre == 'scifi':
        return f'{random.choice(scifi_adj)} {random.choice(scifi_rooms)}'


makename()