# Generated by Django 3.0.4 on 2020-03-30 22:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('north', models.IntegerField(blank=True, null=True)),
                ('south', models.IntegerField(blank=True, null=True)),
                ('east', models.IntegerField(blank=True, null=True)),
                ('west', models.IntegerField(blank=True, null=True)),
                ('map_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adventure.Map')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('health', models.IntegerField(default=100)),
                ('mana', models.IntegerField(default=100)),
                ('stamina', models.IntegerField(default=100)),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adventure.Room')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='map',
            name='player_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adventure.Player'),
        ),
    ]
