# Generated by Django 3.0.5 on 2020-04-02 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='end',
            field=models.BooleanField(default=False),
        ),
    ]
